# Generated by Django 5.1.7 on 2025-03-15 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacao', models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação')], max_length=20, null=True)),
                ('area_interesse', models.CharField(blank=True, choices=[('exatas', 'Ciências Exatas'), ('humanas', 'Ciências Humanas'), ('biologicas', 'Ciências Biológicas'), ('tecnologia', 'Tecnologia'), ('linguagens', 'Linguagens'), ('outros', 'Outros')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
